spring:
  config:
    activate:
      on-profile: test
  datasource:
    url: jdbc:h2:mem:DATABASE;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE;MODE=MYSQL
  flyway:
    locations: 'classpath:db/migration,test_data'
    baseline-on-migrate: true