# Spring boot admin configuration
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---

# internal properties
omdbapi:
  api:
    key: ba73f1b0
    url: http://www.omdbapi.com

---

# Database setup
spring:
  jpa:
    hibernate:
      ddl-auto: validate
  flyway:
    baseline-on-migrate: true
  sql:
    init:
      continue-on-error: true
