version: 2.1

workflows:
  my-workflow:
    jobs:
      - build-and-test:
          context:
            - docker-login

jobs:
  build-and-test:  
    docker:
      - image: cimg/openjdk:16.0.0
    steps:
      - checkout
      - setup_remote_docker:
          version: 19.03.13
      - run:
          name: Setup VirtualEnv
          command: |
            echo 'export TAG=0.1.${CIRCLE_BUILD_NUM}' >> $BASH_ENV
            echo 'export IMAGE_NAME=media-storage' >> $BASH_ENV 
            echo 'export DOCKER_REPOSITORY=repo.treescale.com/jaydamon' >> $BASH_ENV          
      # - setup_remote_docker:
      #     docker_layer_caching: true
      - run:
          name: Build and push Docker image
          command: |
            docker build -t $DOCKER_REPOSITORY/$IMAGE_NAME:$TAG .
            echo $DOCKER_PWD | docker login repo.treescale.com -u $DOCKER_LOGIN --password-stdin 
            docker push $DOCKER_REPOSITORY/$IMAGE_NAME:$TAG

